In [2]:
import pandas as pd

In [3]:
amazon_path = "/Users/COMPUTER/Desktop/cleaned_data/amazon_cleaned_data.csv"
amazon = pd.read_csv(amazon_path)
amazon.head()

,asin,title,imgUrl,productURL,stars,reviews,price,listPrice,category_id,isBestSeller,boughtInLastMonth
0,B014TMV5YE,"Sion Softside Expandable Roller Luggage, Black...",https://m.media-amazon.com/images/I/815dLQKYIY...,https://www.amazon.com/dp/B014TMV5YE,4.5,0,139.99,0.00,104,0,2000
1,B07GDLCQXV,Luggage Sets Expandable PC+ABS Durable Suitcas...,https://m.media-amazon.com/images/I/81bQlm7vf6...,https://www.amazon.com/dp/B07GDLCQXV,4.5,0,169.99,209.99,104,0,1000
2,B07XSCCZYG,Platinum Elite Softside Expandable Checked Lug...,https://m.media-amazon.com/images/I/71EA35zvJB...,https://www.amazon.com/dp/B07XSCCZYG,4.6,0,365.49,429.99,104,0,300
3,B08MVFKGJM,Freeform Hardside Expandable with Double Spinn...,https://m.media-amazon.com/images/I/91k6NYLQyI...,https://www.amazon.com/dp/B08MVFKGJM,4.6,0,291.59,354.37,104,0,400
4,B01DJLKZBA,Winfield 2 Hardside Expandable Luggage with Sp...,https://m.media-amazon.com/images/I/61NJoaZcP9...,https://www.amazon.com/dp/B01DJLKZBA,4.5,0,174.99,309.99,104,0,400

In [4]:
walmart_path = "/Users/COMPUTER/Desktop/cleaned_data/walmart_cleaned_data.csv"
walmart = pd.read_csv(walmart_path)
walmart.head()

,Uniq Id,Product Url,Product Name,Description,List Price,Sale Price,Brand,Category,Available
0,51b010b871cde349bd32159a1cc1a15f,https://www.walmart.com/ip/Allegiance-Economy-...,Allegiance Economy Dual-scale Digital Thermometer,We aim to show you accurate product informati...,11.11,11.11,Cardinal Health,Health | Medicine Cabinet | Thermometers | Dig...,1
1,d6a7f100e44a626a3701804e99236ad6,https://www.walmart.com/ip/Kenneth-Cole-Reacti...,Kenneth Cole Reaction Eau De Parfum Spray For ...,We aim to show you accurate product informati...,23.99,23.99,Kenneth Cole,Premium Beauty | Premium Fragrance | Premium P...,1
2,99d2b7da7e3e427a942f864937dacd9d,https://www.walmart.com/ip/Kid-Tough-Fitness-I...,Kid Tough Fitness Inflatable Free-Standing Pun...,We aim to show you accurate product informati...,30.76,30.76,BONK FIT,Sports & Outdoors | Outdoor Sports | Hunting |...,1
3,4c76d170c2c6a759cbce812d790a0b88,https://www.walmart.com/ip/THE-FIRST-YEARS/167...,THE FIRST YEARS,We aim to show you accurate product informati...,6.99,6.99,The First Years,Baby | Diapering | Baby Wipes,1
4,8ac95837dc8baa01e504fd8f633ffaf2,https://www.walmart.com/ip/4-Pack-MD-USA-Seaml...,4 Pack - MD USA Seamless Toe-Wave-In Mesh Diab...,We aim to show you accurate product informatio...,28.27,28.27,MD USA,Health | Diabetes Care | Diabetic Socks,1

In [7]:
walmart = walmart.drop(['Description', 'Brand'], axis=1)
walmart.head()

,Uniq Id,Product Url,Product Name,List Price,Sale Price,Category,Available
0,51b010b871cde349bd32159a1cc1a15f,https://www.walmart.com/ip/Allegiance-Economy-...,Allegiance Economy Dual-scale Digital Thermometer,11.11,11.11,Health | Medicine Cabinet | Thermometers | Dig...,1
1,d6a7f100e44a626a3701804e99236ad6,https://www.walmart.com/ip/Kenneth-Cole-Reacti...,Kenneth Cole Reaction Eau De Parfum Spray For ...,23.99,23.99,Premium Beauty | Premium Fragrance | Premium P...,1
2,99d2b7da7e3e427a942f864937dacd9d,https://www.walmart.com/ip/Kid-Tough-Fitness-I...,Kid Tough Fitness Inflatable Free-Standing Pun...,30.76,30.76,Sports & Outdoors | Outdoor Sports | Hunting |...,1
3,4c76d170c2c6a759cbce812d790a0b88,https://www.walmart.com/ip/THE-FIRST-YEARS/167...,THE FIRST YEARS,6.99,6.99,Baby | Diapering | Baby Wipes,1
4,8ac95837dc8baa01e504fd8f633ffaf2,https://www.walmart.com/ip/4-Pack-MD-USA-Seaml...,4 Pack - MD USA Seamless Toe-Wave-In Mesh Diab...,28.27,28.27,Health | Diabetes Care | Diabetic Socks,1

In [8]:
walmart = walmart.drop(['Uniq Id', 'List Price'], axis=1)
walmart.head()

,Product Url,Product Name,Sale Price,Category,Available
0,https://www.walmart.com/ip/Allegiance-Economy-...,Allegiance Economy Dual-scale Digital Thermometer,11.11,Health | Medicine Cabinet | Thermometers | Dig...,1
1,https://www.walmart.com/ip/Kenneth-Cole-Reacti...,Kenneth Cole Reaction Eau De Parfum Spray For ...,23.99,Premium Beauty | Premium Fragrance | Premium P...,1
2,https://www.walmart.com/ip/Kid-Tough-Fitness-I...,Kid Tough Fitness Inflatable Free-Standing Pun...,30.76,Sports & Outdoors | Outdoor Sports | Hunting |...,1
3,https://www.walmart.com/ip/THE-FIRST-YEARS/167...,THE FIRST YEARS,6.99,Baby | Diapering | Baby Wipes,1
4,https://www.walmart.com/ip/4-Pack-MD-USA-Seaml...,4 Pack - MD USA Seamless Toe-Wave-In Mesh Diab...,28.27,Health | Diabetes Care | Diabetic Socks,1

In [5]:
shein_path = "/Users/COMPUTER/Desktop/cleaned_data/shein_cleaned_data.csv"
shein = pd.read_csv(shein_path)
shein.head()

,Unnamed: 0,url,name,price,brand,description,images
0,0,https://us.shein.com/Flower-Decor-Face-Coverin...,Flower Decor Face Covering Chain,$2.50,QingSang Accessories Apparel Accessories,"[{'Color': 'Multicolor'}, {'Material': 'PMMA'}]",['https://storage.yandexcloud.net/clothes-and-...
1,1,https://us.shein.com/Lace-Up-Bodycon-Skirt-p-7...,Lace Up Bodycon Skirt,$7.25,NaN,"[{'Color': 'Black'}, {'Style': 'Sexy'}, {'Patt...",['https://storage.yandexcloud.net/clothes-and-...
2,2,https://us.shein.com/High-Waist-Twist-Front-Sh...,High Waist Twist Front Shorts,$8.99,NaN,"[{'Color': 'Royal Blue'}, {'Style': 'Casual'},...",['https://storage.yandexcloud.net/clothes-and-...
3,3,https://us.shein.com/ROMWE-Sweetness-Cherry-La...,ROMWE Sweetness Cherry Lace Cami Top,$7.00,ROMWE,"[{'Color': 'Red and White'}, {'Style': 'Casual...",['https://storage.yandexcloud.net/clothes-and-...
4,4,https://us.shein.com/Cut-Out-Criss-Cross-One-P...,Cut Out Criss Cross One Piece Swimsuit,$9.50,NaN,"[{'Color': 'Lilac Purple'}, {'Style': 'Elegant...",['https://storage.yandexcloud.net/clothes-and-...

In [ ]:
shein = shein.drop(['brand'], axis=1)

In [6]:
temu_path = "/Users/COMPUTER/Desktop/cleaned_data/temu_cleaned_data.csv"
temu = pd.read_csv(temu_path)
temu.head()

,Unnamed: 0,leve_1_category_id,leve_1_category_name,leve_2_category_id,leve_2_category_name,title,category_id,visible,sales_volume,price,goods_score,comment_num
0,0,885,"Patio, Lawn & Garden",888,Outdoor Supplies & Patio Furniture,1pc 30 LED Bubble Ball Lights Solar String Lig...,891,True,5560.0,6.55,4.7,200.0
1,1,885,"Patio, Lawn & Garden",888,Outdoor Supplies & Patio Furniture,50 LED Solar Sakura Lights Outdoor Waterproof ...,891,True,3569.0,5.89,4.7,200.0
2,2,885,"Patio, Lawn & Garden",888,Outdoor Supplies & Patio Furniture,10m 20m 30m Solar Copper Wire String Light Hol...,891,True,2364.0,4.89,4.7,200.0
3,3,885,"Patio, Lawn & Garden",888,Outdoor Supplies & Patio Furniture,"LED String Lights, Battery Operated Copper Wir...",891,True,538.0,1.59,5.0,1.0
4,4,885,"Patio, Lawn & Garden",888,Outdoor Supplies & Patio Furniture,"1pc 39ft 100LED Solar String Lights, Waterproo...",891,True,474.0,8.39,4.7,200.0

In [9]:
temu = temu.drop(['comment_num', 'visible', 'comment_num'], axis=1)
temu.head()

,Unnamed: 0,leve_1_category_id,leve_1_category_name,leve_2_category_id,leve_2_category_name,title,category_id,sales_volume,price,goods_score
0,0,885,"Patio, Lawn & Garden",888,Outdoor Supplies & Patio Furniture,1pc 30 LED Bubble Ball Lights Solar String Lig...,891,5560.0,6.55,4.7
1,1,885,"Patio, Lawn & Garden",888,Outdoor Supplies & Patio Furniture,50 LED Solar Sakura Lights Outdoor Waterproof ...,891,3569.0,5.89,4.7
2,2,885,"Patio, Lawn & Garden",888,Outdoor Supplies & Patio Furniture,10m 20m 30m Solar Copper Wire String Light Hol...,891,2364.0,4.89,4.7
3,3,885,"Patio, Lawn & Garden",888,Outdoor Supplies & Patio Furniture,"LED String Lights, Battery Operated Copper Wir...",891,538.0,1.59,5.0
4,4,885,"Patio, Lawn & Garden",888,Outdoor Supplies & Patio Furniture,"1pc 39ft 100LED Solar String Lights, Waterproo...",891,474.0,8.39,4.7

In [ ]:
temu = temu.drop(['leve_1_category_id','leve_2_category_id', 'category_id'], axis=1)

In [14]:
temu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95189 entries, 0 to 95188
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   leve_1_category_name  95189 non-null  object
 1   leve_2_category_name  95189 non-null  object
 2   title                 95189 non-null  object
 3   sales_volume          93480 non-null  float64
 4   price                 95189 non-null  float64
 5   goods_score           81070 non-null  float64
dtypes: float64(3), object(3)
memory usage: 4.4+ MB

In [15]:
temu.head()

,leve_1_category_name,leve_2_category_name,title,sales_volume,price,goods_score
0,"Patio, Lawn & Garden",Outdoor Supplies & Patio Furniture,1pc 30 LED Bubble Ball Lights Solar String Lig...,5560.0,6.55,4.7
1,"Patio, Lawn & Garden",Outdoor Supplies & Patio Furniture,50 LED Solar Sakura Lights Outdoor Waterproof ...,3569.0,5.89,4.7
2,"Patio, Lawn & Garden",Outdoor Supplies & Patio Furniture,10m 20m 30m Solar Copper Wire String Light Hol...,2364.0,4.89,4.7
3,"Patio, Lawn & Garden",Outdoor Supplies & Patio Furniture,"LED String Lights, Battery Operated Copper Wir...",538.0,1.59,5.0
4,"Patio, Lawn & Garden",Outdoor Supplies & Patio Furniture,"1pc 39ft 100LED Solar String Lights, Waterproo...",474.0,8.39,4.7

In [16]:
amazon.head()

,asin,title,imgUrl,productURL,stars,reviews,price,listPrice,category_id,isBestSeller,boughtInLastMonth
0,B014TMV5YE,"Sion Softside Expandable Roller Luggage, Black...",https://m.media-amazon.com/images/I/815dLQKYIY...,https://www.amazon.com/dp/B014TMV5YE,4.5,0,139.99,0.00,104,0,2000
1,B07GDLCQXV,Luggage Sets Expandable PC+ABS Durable Suitcas...,https://m.media-amazon.com/images/I/81bQlm7vf6...,https://www.amazon.com/dp/B07GDLCQXV,4.5,0,169.99,209.99,104,0,1000
2,B07XSCCZYG,Platinum Elite Softside Expandable Checked Lug...,https://m.media-amazon.com/images/I/71EA35zvJB...,https://www.amazon.com/dp/B07XSCCZYG,4.6,0,365.49,429.99,104,0,300
3,B08MVFKGJM,Freeform Hardside Expandable with Double Spinn...,https://m.media-amazon.com/images/I/91k6NYLQyI...,https://www.amazon.com/dp/B08MVFKGJM,4.6,0,291.59,354.37,104,0,400
4,B01DJLKZBA,Winfield 2 Hardside Expandable Luggage with Sp...,https://m.media-amazon.com/images/I/61NJoaZcP9...,https://www.amazon.com/dp/B01DJLKZBA,4.5,0,174.99,309.99,104,0,400

In [17]:
amazon = amazon.drop(['asin','reviews', 'listPrice','isBestSeller'], axis=1)

In [18]:
amazon.head()

,title,imgUrl,productURL,stars,price,category_id,boughtInLastMonth
0,"Sion Softside Expandable Roller Luggage, Black...",https://m.media-amazon.com/images/I/815dLQKYIY...,https://www.amazon.com/dp/B014TMV5YE,4.5,139.99,104,2000
1,Luggage Sets Expandable PC+ABS Durable Suitcas...,https://m.media-amazon.com/images/I/81bQlm7vf6...,https://www.amazon.com/dp/B07GDLCQXV,4.5,169.99,104,1000
2,Platinum Elite Softside Expandable Checked Lug...,https://m.media-amazon.com/images/I/71EA35zvJB...,https://www.amazon.com/dp/B07XSCCZYG,4.6,365.49,104,300
3,Freeform Hardside Expandable with Double Spinn...,https://m.media-amazon.com/images/I/91k6NYLQyI...,https://www.amazon.com/dp/B08MVFKGJM,4.6,291.59,104,400
4,Winfield 2 Hardside Expandable Luggage with Sp...,https://m.media-amazon.com/images/I/61NJoaZcP9...,https://www.amazon.com/dp/B01DJLKZBA,4.5,174.99,104,400

In [19]:
shein.head()

,Unnamed: 0,url,name,price,brand,description,images
0,0,https://us.shein.com/Flower-Decor-Face-Coverin...,Flower Decor Face Covering Chain,$2.50,QingSang Accessories Apparel Accessories,"[{'Color': 'Multicolor'}, {'Material': 'PMMA'}]",['https://storage.yandexcloud.net/clothes-and-...
1,1,https://us.shein.com/Lace-Up-Bodycon-Skirt-p-7...,Lace Up Bodycon Skirt,$7.25,NaN,"[{'Color': 'Black'}, {'Style': 'Sexy'}, {'Patt...",['https://storage.yandexcloud.net/clothes-and-...
2,2,https://us.shein.com/High-Waist-Twist-Front-Sh...,High Waist Twist Front Shorts,$8.99,NaN,"[{'Color': 'Royal Blue'}, {'Style': 'Casual'},...",['https://storage.yandexcloud.net/clothes-and-...
3,3,https://us.shein.com/ROMWE-Sweetness-Cherry-La...,ROMWE Sweetness Cherry Lace Cami Top,$7.00,ROMWE,"[{'Color': 'Red and White'}, {'Style': 'Casual...",['https://storage.yandexcloud.net/clothes-and-...
4,4,https://us.shein.com/Cut-Out-Criss-Cross-One-P...,Cut Out Criss Cross One Piece Swimsuit,$9.50,NaN,"[{'Color': 'Lilac Purple'}, {'Style': 'Elegant...",['https://storage.yandexcloud.net/clothes-and-...

In [20]:
shein = shein.drop(['brand', 'Unnamed: 0'], axis=1)

In [24]:
shein = shein.drop(['images'], axis=1)
shein.head()

,url,name,price,description
0,https://us.shein.com/Flower-Decor-Face-Coverin...,Flower Decor Face Covering Chain,$2.50,"[{'Color': 'Multicolor'}, {'Material': 'PMMA'}]"
1,https://us.shein.com/Lace-Up-Bodycon-Skirt-p-7...,Lace Up Bodycon Skirt,$7.25,"[{'Color': 'Black'}, {'Style': 'Sexy'}, {'Patt..."
2,https://us.shein.com/High-Waist-Twist-Front-Sh...,High Waist Twist Front Shorts,$8.99,"[{'Color': 'Royal Blue'}, {'Style': 'Casual'},..."
3,https://us.shein.com/ROMWE-Sweetness-Cherry-La...,ROMWE Sweetness Cherry Lace Cami Top,$7.00,"[{'Color': 'Red and White'}, {'Style': 'Casual..."
4,https://us.shein.com/Cut-Out-Criss-Cross-One-P...,Cut Out Criss Cross One Piece Swimsuit,$9.50,"[{'Color': 'Lilac Purple'}, {'Style': 'Elegant..."

In [22]:
walmart.head()

,Product Url,Product Name,Sale Price,Category,Available
0,https://www.walmart.com/ip/Allegiance-Economy-...,Allegiance Economy Dual-scale Digital Thermometer,11.11,Health | Medicine Cabinet | Thermometers | Dig...,1
1,https://www.walmart.com/ip/Kenneth-Cole-Reacti...,Kenneth Cole Reaction Eau De Parfum Spray For ...,23.99,Premium Beauty | Premium Fragrance | Premium P...,1
2,https://www.walmart.com/ip/Kid-Tough-Fitness-I...,Kid Tough Fitness Inflatable Free-Standing Pun...,30.76,Sports & Outdoors | Outdoor Sports | Hunting |...,1
3,https://www.walmart.com/ip/THE-FIRST-YEARS/167...,THE FIRST YEARS,6.99,Baby | Diapering | Baby Wipes,1
4,https://www.walmart.com/ip/4-Pack-MD-USA-Seaml...,4 Pack - MD USA Seamless Toe-Wave-In Mesh Diab...,28.27,Health | Diabetes Care | Diabetic Socks,1

In [23]:
walmart = walmart.drop(['Available'], axis=1)
walmart.head()

,Product Url,Product Name,Sale Price,Category
0,https://www.walmart.com/ip/Allegiance-Economy-...,Allegiance Economy Dual-scale Digital Thermometer,11.11,Health | Medicine Cabinet | Thermometers | Dig...
1,https://www.walmart.com/ip/Kenneth-Cole-Reacti...,Kenneth Cole Reaction Eau De Parfum Spray For ...,23.99,Premium Beauty | Premium Fragrance | Premium P...
2,https://www.walmart.com/ip/Kid-Tough-Fitness-I...,Kid Tough Fitness Inflatable Free-Standing Pun...,30.76,Sports & Outdoors | Outdoor Sports | Hunting |...
3,https://www.walmart.com/ip/THE-FIRST-YEARS/167...,THE FIRST YEARS,6.99,Baby | Diapering | Baby Wipes
4,https://www.walmart.com/ip/4-Pack-MD-USA-Seaml...,4 Pack - MD USA Seamless Toe-Wave-In Mesh Diab...,28.27,Health | Diabetes Care | Diabetic Socks

In [25]:
shein.head()

,url,name,price,description
0,https://us.shein.com/Flower-Decor-Face-Coverin...,Flower Decor Face Covering Chain,$2.50,"[{'Color': 'Multicolor'}, {'Material': 'PMMA'}]"
1,https://us.shein.com/Lace-Up-Bodycon-Skirt-p-7...,Lace Up Bodycon Skirt,$7.25,"[{'Color': 'Black'}, {'Style': 'Sexy'}, {'Patt..."
2,https://us.shein.com/High-Waist-Twist-Front-Sh...,High Waist Twist Front Shorts,$8.99,"[{'Color': 'Royal Blue'}, {'Style': 'Casual'},..."
3,https://us.shein.com/ROMWE-Sweetness-Cherry-La...,ROMWE Sweetness Cherry Lace Cami Top,$7.00,"[{'Color': 'Red and White'}, {'Style': 'Casual..."
4,https://us.shein.com/Cut-Out-Criss-Cross-One-P...,Cut Out Criss Cross One Piece Swimsuit,$9.50,"[{'Color': 'Lilac Purple'}, {'Style': 'Elegant..."

In [26]:
temu = temu.drop(['brand'], axis=1)
temu.head()

,leve_1_category_name,leve_2_category_name,title,sales_volume,price,goods_score
0,"Patio, Lawn & Garden",Outdoor Supplies & Patio Furniture,1pc 30 LED Bubble Ball Lights Solar String Lig...,5560.0,6.55,4.7
1,"Patio, Lawn & Garden",Outdoor Supplies & Patio Furniture,50 LED Solar Sakura Lights Outdoor Waterproof ...,3569.0,5.89,4.7
2,"Patio, Lawn & Garden",Outdoor Supplies & Patio Furniture,10m 20m 30m Solar Copper Wire String Light Hol...,2364.0,4.89,4.7
3,"Patio, Lawn & Garden",Outdoor Supplies & Patio Furniture,"LED String Lights, Battery Operated Copper Wir...",538.0,1.59,5.0
4,"Patio, Lawn & Garden",Outdoor Supplies & Patio Furniture,"1pc 39ft 100LED Solar String Lights, Waterproo...",474.0,8.39,4.7

In [28]:
amazon = amazon.drop(['imgUrl'], axis=1)
amazon.head()

,title,productURL,stars,price,category_id,boughtInLastMonth
0,"Sion Softside Expandable Roller Luggage, Black...",https://www.amazon.com/dp/B014TMV5YE,4.5,139.99,104,2000
1,Luggage Sets Expandable PC+ABS Durable Suitcas...,https://www.amazon.com/dp/B07GDLCQXV,4.5,169.99,104,1000
2,Platinum Elite Softside Expandable Checked Lug...,https://www.amazon.com/dp/B07XSCCZYG,4.6,365.49,104,300
3,Freeform Hardside Expandable with Double Spinn...,https://www.amazon.com/dp/B08MVFKGJM,4.6,291.59,104,400
4,Winfield 2 Hardside Expandable Luggage with Sp...,https://www.amazon.com/dp/B01DJLKZBA,4.5,174.99,104,400

In [29]:
temu.head()

,leve_1_category_name,leve_2_category_name,title,sales_volume,price,goods_score
0,"Patio, Lawn & Garden",Outdoor Supplies & Patio Furniture,1pc 30 LED Bubble Ball Lights Solar String Lig...,5560.0,6.55,4.7
1,"Patio, Lawn & Garden",Outdoor Supplies & Patio Furniture,50 LED Solar Sakura Lights Outdoor Waterproof ...,3569.0,5.89,4.7
2,"Patio, Lawn & Garden",Outdoor Supplies & Patio Furniture,10m 20m 30m Solar Copper Wire String Light Hol...,2364.0,4.89,4.7
3,"Patio, Lawn & Garden",Outdoor Supplies & Patio Furniture,"LED String Lights, Battery Operated Copper Wir...",538.0,1.59,5.0
4,"Patio, Lawn & Garden",Outdoor Supplies & Patio Furniture,"1pc 39ft 100LED Solar String Lights, Waterproo...",474.0,8.39,4.7

In [30]:
shein.head()

,url,name,price,description
0,https://us.shein.com/Flower-Decor-Face-Coverin...,Flower Decor Face Covering Chain,$2.50,"[{'Color': 'Multicolor'}, {'Material': 'PMMA'}]"
1,https://us.shein.com/Lace-Up-Bodycon-Skirt-p-7...,Lace Up Bodycon Skirt,$7.25,"[{'Color': 'Black'}, {'Style': 'Sexy'}, {'Patt..."
2,https://us.shein.com/High-Waist-Twist-Front-Sh...,High Waist Twist Front Shorts,$8.99,"[{'Color': 'Royal Blue'}, {'Style': 'Casual'},..."
3,https://us.shein.com/ROMWE-Sweetness-Cherry-La...,ROMWE Sweetness Cherry Lace Cami Top,$7.00,"[{'Color': 'Red and White'}, {'Style': 'Casual..."
4,https://us.shein.com/Cut-Out-Criss-Cross-One-P...,Cut Out Criss Cross One Piece Swimsuit,$9.50,"[{'Color': 'Lilac Purple'}, {'Style': 'Elegant..."

In [31]:
walmart.head()

,Product Url,Product Name,Sale Price,Category
0,https://www.walmart.com/ip/Allegiance-Economy-...,Allegiance Economy Dual-scale Digital Thermometer,11.11,Health | Medicine Cabinet | Thermometers | Dig...
1,https://www.walmart.com/ip/Kenneth-Cole-Reacti...,Kenneth Cole Reaction Eau De Parfum Spray For ...,23.99,Premium Beauty | Premium Fragrance | Premium P...
2,https://www.walmart.com/ip/Kid-Tough-Fitness-I...,Kid Tough Fitness Inflatable Free-Standing Pun...,30.76,Sports & Outdoors | Outdoor Sports | Hunting |...
3,https://www.walmart.com/ip/THE-FIRST-YEARS/167...,THE FIRST YEARS,6.99,Baby | Diapering | Baby Wipes
4,https://www.walmart.com/ip/4-Pack-MD-USA-Seaml...,4 Pack - MD USA Seamless Toe-Wave-In Mesh Diab...,28.27,Health | Diabetes Care | Diabetic Socks

In [32]:
temu.head()

,leve_1_category_name,leve_2_category_name,title,sales_volume,price,goods_score
0,"Patio, Lawn & Garden",Outdoor Supplies & Patio Furniture,1pc 30 LED Bubble Ball Lights Solar String Lig...,5560.0,6.55,4.7
1,"Patio, Lawn & Garden",Outdoor Supplies & Patio Furniture,50 LED Solar Sakura Lights Outdoor Waterproof ...,3569.0,5.89,4.7
2,"Patio, Lawn & Garden",Outdoor Supplies & Patio Furniture,10m 20m 30m Solar Copper Wire String Light Hol...,2364.0,4.89,4.7
3,"Patio, Lawn & Garden",Outdoor Supplies & Patio Furniture,"LED String Lights, Battery Operated Copper Wir...",538.0,1.59,5.0
4,"Patio, Lawn & Garden",Outdoor Supplies & Patio Furniture,"1pc 39ft 100LED Solar String Lights, Waterproo...",474.0,8.39,4.7

In [33]:
temu = temu.drop(['leve_1_category_name'], axis=1)
temu.head()

,leve_2_category_name,title,sales_volume,price,goods_score
0,Outdoor Supplies & Patio Furniture,1pc 30 LED Bubble Ball Lights Solar String Lig...,5560.0,6.55,4.7
1,Outdoor Supplies & Patio Furniture,50 LED Solar Sakura Lights Outdoor Waterproof ...,3569.0,5.89,4.7
2,Outdoor Supplies & Patio Furniture,10m 20m 30m Solar Copper Wire String Light Hol...,2364.0,4.89,4.7
3,Outdoor Supplies & Patio Furniture,"LED String Lights, Battery Operated Copper Wir...",538.0,1.59,5.0
4,Outdoor Supplies & Patio Furniture,"1pc 39ft 100LED Solar String Lights, Waterproo...",474.0,8.39,4.7

In [34]:
amazon_categories_path = "/Users/COMPUTER/PycharmProjects/pythonProject2/datasets/amazon_categories.csv"
amazon_categories = pd.read_csv(amazon_categories_path)
amazon_categories.head()

   id                     category_name
0   1          Beading & Jewelry Making
1   2                 Fabric Decorating
2   3       Knitting & Crochet Supplies
3   4              Printmaking Supplies
4   5  Scrapbooking & Stamping Supplies

In [36]:
amazon_with_category = pd.merge(amazon, amazon_categories, left_on='category_id', right_on='id', how='left')
amazon_with_category.head()

,title,productURL,stars,price,category_id,boughtInLastMonth,id,category_name
0,"Sion Softside Expandable Roller Luggage, Black...",https://www.amazon.com/dp/B014TMV5YE,4.5,139.99,104,2000,104,Suitcases
1,Luggage Sets Expandable PC+ABS Durable Suitcas...,https://www.amazon.com/dp/B07GDLCQXV,4.5,169.99,104,1000,104,Suitcases
2,Platinum Elite Softside Expandable Checked Lug...,https://www.amazon.com/dp/B07XSCCZYG,4.6,365.49,104,300,104,Suitcases
3,Freeform Hardside Expandable with Double Spinn...,https://www.amazon.com/dp/B08MVFKGJM,4.6,291.59,104,400,104,Suitcases
4,Winfield 2 Hardside Expandable Luggage with Sp...,https://www.amazon.com/dp/B01DJLKZBA,4.5,174.99,104,400,104,Suitcases

In [37]:
amazon_with_category = amazon_with_category.drop(['category_id','id'], axis = 1)
amazon_with_category.head()

,title,productURL,stars,price,boughtInLastMonth,category_name
0,"Sion Softside Expandable Roller Luggage, Black...",https://www.amazon.com/dp/B014TMV5YE,4.5,139.99,2000,Suitcases
1,Luggage Sets Expandable PC+ABS Durable Suitcas...,https://www.amazon.com/dp/B07GDLCQXV,4.5,169.99,1000,Suitcases
2,Platinum Elite Softside Expandable Checked Lug...,https://www.amazon.com/dp/B07XSCCZYG,4.6,365.49,300,Suitcases
3,Freeform Hardside Expandable with Double Spinn...,https://www.amazon.com/dp/B08MVFKGJM,4.6,291.59,400,Suitcases
4,Winfield 2 Hardside Expandable Luggage with Sp...,https://www.amazon.com/dp/B01DJLKZBA,4.5,174.99,400,Suitcases

In [38]:
walmart.head()

,Product Url,Product Name,Sale Price,Category
0,https://www.walmart.com/ip/Allegiance-Economy-...,Allegiance Economy Dual-scale Digital Thermometer,11.11,Health | Medicine Cabinet | Thermometers | Dig...
1,https://www.walmart.com/ip/Kenneth-Cole-Reacti...,Kenneth Cole Reaction Eau De Parfum Spray For ...,23.99,Premium Beauty | Premium Fragrance | Premium P...
2,https://www.walmart.com/ip/Kid-Tough-Fitness-I...,Kid Tough Fitness Inflatable Free-Standing Pun...,30.76,Sports & Outdoors | Outdoor Sports | Hunting |...
3,https://www.walmart.com/ip/THE-FIRST-YEARS/167...,THE FIRST YEARS,6.99,Baby | Diapering | Baby Wipes
4,https://www.walmart.com/ip/4-Pack-MD-USA-Seaml...,4 Pack - MD USA Seamless Toe-Wave-In Mesh Diab...,28.27,Health | Diabetes Care | Diabetic Socks

In [39]:
temu.head()

,leve_2_category_name,title,sales_volume,price,goods_score
0,Outdoor Supplies & Patio Furniture,1pc 30 LED Bubble Ball Lights Solar String Lig...,5560.0,6.55,4.7
1,Outdoor Supplies & Patio Furniture,50 LED Solar Sakura Lights Outdoor Waterproof ...,3569.0,5.89,4.7
2,Outdoor Supplies & Patio Furniture,10m 20m 30m Solar Copper Wire String Light Hol...,2364.0,4.89,4.7
3,Outdoor Supplies & Patio Furniture,"LED String Lights, Battery Operated Copper Wir...",538.0,1.59,5.0
4,Outdoor Supplies & Patio Furniture,"1pc 39ft 100LED Solar String Lights, Waterproo...",474.0,8.39,4.7

In [40]:
shein.head()

,url,name,price,description
0,https://us.shein.com/Flower-Decor-Face-Coverin...,Flower Decor Face Covering Chain,$2.50,"[{'Color': 'Multicolor'}, {'Material': 'PMMA'}]"
1,https://us.shein.com/Lace-Up-Bodycon-Skirt-p-7...,Lace Up Bodycon Skirt,$7.25,"[{'Color': 'Black'}, {'Style': 'Sexy'}, {'Patt..."
2,https://us.shein.com/High-Waist-Twist-Front-Sh...,High Waist Twist Front Shorts,$8.99,"[{'Color': 'Royal Blue'}, {'Style': 'Casual'},..."
3,https://us.shein.com/ROMWE-Sweetness-Cherry-La...,ROMWE Sweetness Cherry Lace Cami Top,$7.00,"[{'Color': 'Red and White'}, {'Style': 'Casual..."
4,https://us.shein.com/Cut-Out-Criss-Cross-One-P...,Cut Out Criss Cross One Piece Swimsuit,$9.50,"[{'Color': 'Lilac Purple'}, {'Style': 'Elegant..."

In [41]:
#create unique identifier for all products
temu['UID'] = ['T' + str(i) for i in range(len(temu))]
walmart['UID'] = ['W' + str(i) for i in range(len(walmart))]
amazon_with_category['UID'] = ['A' + str(i) for i in range(len(amazon_with_category))]
shein['UID'] = ['S' + str(i) for i in range(len(shein))]

In [42]:
temu.head()

,leve_2_category_name,title,sales_volume,price,goods_score,UID
0,Outdoor Supplies & Patio Furniture,1pc 30 LED Bubble Ball Lights Solar String Lig...,5560.0,6.55,4.7,T0
1,Outdoor Supplies & Patio Furniture,50 LED Solar Sakura Lights Outdoor Waterproof ...,3569.0,5.89,4.7,T1
2,Outdoor Supplies & Patio Furniture,10m 20m 30m Solar Copper Wire String Light Hol...,2364.0,4.89,4.7,T2
3,Outdoor Supplies & Patio Furniture,"LED String Lights, Battery Operated Copper Wir...",538.0,1.59,5.0,T3
4,Outdoor Supplies & Patio Furniture,"1pc 39ft 100LED Solar String Lights, Waterproo...",474.0,8.39,4.7,T4

In [43]:
# Standardize and select necessary columns
temu_standardized = temu.rename(columns={'title': 'Title', 'price': 'Price'})[['UID', 'Title', 'Price']]
walmart_standardized = walmart.rename(columns={'Product Name': 'Title', 'Sale Price': 'Price'})[['UID', 'Title', 'Price']]
amazon_standardized = amazon_with_category.rename(columns={'title': 'Title', 'price': 'Price'})[['UID', 'Title', 'Price']]
shein_standardized = shein.rename(columns={'name': 'Title', 'price': 'Price'})[['UID', 'Title', 'Price']]

In [44]:
temu_standardized.head()

  UID                                              Title  Price
0  T0  1pc 30 LED Bubble Ball Lights Solar String Lig...   6.55
1  T1  50 LED Solar Sakura Lights Outdoor Waterproof ...   5.89
2  T2  10m 20m 30m Solar Copper Wire String Light Hol...   4.89
3  T3  LED String Lights, Battery Operated Copper Wir...   1.59
4  T4  1pc 39ft 100LED Solar String Lights, Waterproo...   8.39

In [46]:
# Combine all dataframes
Main = pd.concat([temu_standardized, walmart_standardized, amazon_standardized, shein_standardized], ignore_index=True)
Main.head()

  UID                                              Title Price
0  T0  1pc 30 LED Bubble Ball Lights Solar String Lig...  6.55
1  T1  50 LED Solar Sakura Lights Outdoor Waterproof ...  5.89
2  T2  10m 20m 30m Solar Copper Wire String Light Hol...  4.89
3  T3  LED String Lights, Battery Operated Copper Wir...  1.59
4  T4  1pc 39ft 100LED Solar String Lights, Waterproo...  8.39

In [47]:
amazon_with_category['URL'] = amazon_with_category['productURL']
shein['URL'] = shein['url']
walmart['URL'] = walmart['Product Url']

In [48]:
shein.head()

,url,name,price,description,UID,URL
0,https://us.shein.com/Flower-Decor-Face-Coverin...,Flower Decor Face Covering Chain,$2.50,"[{'Color': 'Multicolor'}, {'Material': 'PMMA'}]",S0,https://us.shein.com/Flower-Decor-Face-Coverin...
1,https://us.shein.com/Lace-Up-Bodycon-Skirt-p-7...,Lace Up Bodycon Skirt,$7.25,"[{'Color': 'Black'}, {'Style': 'Sexy'}, {'Patt...",S1,https://us.shein.com/Lace-Up-Bodycon-Skirt-p-7...
2,https://us.shein.com/High-Waist-Twist-Front-Sh...,High Waist Twist Front Shorts,$8.99,"[{'Color': 'Royal Blue'}, {'Style': 'Casual'},...",S2,https://us.shein.com/High-Waist-Twist-Front-Sh...
3,https://us.shein.com/ROMWE-Sweetness-Cherry-La...,ROMWE Sweetness Cherry Lace Cami Top,$7.00,"[{'Color': 'Red and White'}, {'Style': 'Casual...",S3,https://us.shein.com/ROMWE-Sweetness-Cherry-La...
4,https://us.shein.com/Cut-Out-Criss-Cross-One-P...,Cut Out Criss Cross One Piece Swimsuit,$9.50,"[{'Color': 'Lilac Purple'}, {'Style': 'Elegant...",S4,https://us.shein.com/Cut-Out-Criss-Cross-One-P...

In [49]:
URL = pd.concat([
    amazon_with_category[['UID', 'URL']],
    shein[['UID', 'URL']],
    walmart[['UID', 'URL']],
], ignore_index=True)
URL.head()

  UID                                   URL
0  A0  https://www.amazon.com/dp/B014TMV5YE
1  A1  https://www.amazon.com/dp/B07GDLCQXV
2  A2  https://www.amazon.com/dp/B07XSCCZYG
3  A3  https://www.amazon.com/dp/B08MVFKGJM
4  A4  https://www.amazon.com/dp/B01DJLKZBA

In [51]:
Main['UID'].is_unique

True

In [53]:
temu['Rating'] = temu['goods_score']
temu['Sales'] = temu['sales_volume']
amazon_with_category['Rating'] = amazon_with_category['stars']
amazon_with_category['Sales'] = amazon_with_category['boughtInLastMonth']

Rating_Sales = pd.concat([
    temu[['UID', 'Rating', 'Sales']],
    amazon_with_category[['UID', 'Rating', 'Sales']],
], ignore_index=True)

In [54]:
Rating_Sales.head()

  UID  Rating   Sales
0  T0     4.7  5560.0
1  T1     4.7  3569.0
2  T2     4.7  2364.0
3  T3     5.0   538.0
4  T4     4.7   474.0

In [55]:
amazon_with_category['Keywords'] = amazon_with_category['category_name']
walmart['Keywords'] = walmart['Category']
temu['Keywords'] = temu['leve_2_category_name']
shein['Keywords'] = shein['description']

Keywords = pd.concat([
    amazon_with_category[['UID', 'Keywords']],
    walmart[['UID', 'Keywords']],
    temu[['UID', 'Keywords']],
    shein[['UID', 'Keywords']],
], ignore_index=True)

In [56]:
Keywords.head()

  UID   Keywords
0  A0  Suitcases
1  A1  Suitcases
2  A2  Suitcases
3  A3  Suitcases
4  A4  Suitcases

In [59]:
# Check if any 'Keywords' entry is longer than 255 characters
long_keywords = Keywords['Keywords'].str.len() > 255

# Check if there's any True in long_keywords
long_keywords.any()

True

In [60]:
# Check if any 'URL' entry is longer than 255 characters
long_URL = URL['URL'].str.len() > 255

# Check if there's any True in long_URL
long_URL.any()

True

In [61]:
# Check if any 'Title' entry is longer than 255 characters
long_Title = Main['Title'].str.len() > 255

# Check if there's any True in long_URL
long_Title.any()

True

In [62]:
long_Title.sum()

812

In [63]:
long_keywords.sum()

91053

In [64]:
long_URL.sum()

48

In [65]:
# Check if any 'UID' entry is longer than 255 characters
long_UID = Main['UID'].str.len() > 255

# Check if there's any True in long_URL
long_UID.any()

False

In [67]:
Main.head()

  UID                                              Title Price
0  T0  1pc 30 LED Bubble Ball Lights Solar String Lig...  6.55
1  T1  50 LED Solar Sakura Lights Outdoor Waterproof ...  5.89
2  T2  10m 20m 30m Solar Copper Wire String Light Hol...  4.89
3  T3  LED String Lights, Battery Operated Copper Wir...  1.59
4  T4  1pc 39ft 100LED Solar String Lights, Waterproo...  8.39

In [70]:
Main.to_csv('/Users/COMPUTER/Desktop/Final Data!!!!/Main.csv', index=False)

In [71]:
URL.to_csv('/Users/COMPUTER/Desktop/Final Data!!!!/URL.csv', index=False)
Keywords.to_csv('/Users/COMPUTER/Desktop/Final Data!!!!/Keywords.csv', index=False)
Rating_Sales.to_csv('/Users/COMPUTER/Desktop/Final Data!!!!/Rating_Sales.csv', index=False)